### ISSUE TITLE
i am so confused

### ISSUE THREAD

**Issue by THESTORMZ** [sm64js/sm64js-mmo-server#41]
i am trying to figure out:
1. does this come with the client 
2. do i need a server
3. can i run this on my rpi

**Comment by AgentXLP** [comment]
If you come join the sm64js Discord we could probably help you out.
https://discord.gg/7UaDnJt

**Comment by uuphoria** [comment]
what's an rpi? and you have to get the client from the sm64js repo if you just git clone the server the client folder will be empty by default and "do i need a server" this is the server that you run

**Comment by StormyNotFound** [comment]
> what's an rpi? and you have to get the client from the sm64js repo if you just git clone the server the client folder will be empty by default and "do i need a server" this is the server that you run

I'm on my new acc. but a rpi is a Raspberry Pi SBC (single board computer) that runs on an arm CPU and is around the size of a credit card.  it being so specific limits a large amount of software from running on the system. it was setup as a server computer running a python http server that i was port forwarding. i was wondering if a needed a specific server setup to run this software, my wording was just kind of bad before.

**Comment by StormyNotFound** [comment]
I'm also not really worried about it anymore as my rpi broke a bit ago, it's been replaced by an X86_64 computer.

**Comment by uuphoria** [comment]
The main thing the sm64js-mmo-server requires, is rust The base client in the client folder mainly is nodeJS :P hope that cleared up any confusion

> I'm also not really worried about it anymore as my rpi broke a bit ago, it's been replaced by an X86_64 computer.

**Comment by queenkoopa8500** [comment]
> I'm also not really worried about it anymore as my rpi broke a bit ago, it's been replaced by an X86_64 computer.

Hey stormy, if you ever decide to try to run this repo again (cause it can run on X86_64) then simply use the README.md (thats what I did and it worked)
