### ISSUE TITLE
Im so lost

### ISSUE THREAD

**Issue by queenkoopa8500** [sm64js/sm64js-mmo-server#49]
[irrelavent]

**Comment by uuphoria2** [comment]
Also note that I do have google oauth2 client id and the google oauth2 secret setup in my .env (I have my own for sm64jsarchive and localhost support on it too like http://localhost:3060 so signins work fine)

**Comment by uuphoria2** [comment]
@Tarnadas Mr Reder, please review this whenever you can.

**Comment by uuphoria2** [comment]
Also the client and npm run build which contains `/dist/` is setup so that its fully production-ready for https://mmo.sm64jsarchive.com also @Tarnadas I basically want to serve it to production https://mmo.sm64jsarchive.com using actix web server here to fully serve it and deploy it like that. (sm64js-mmo-server uses actix very nice.)

**Comment by uuphoria2** [comment]
As I am using the sm64js-mmo-server repo and basically want to serve it from my file system to deploy it officially to https://mmo.sm64jsarchive.com for production via Actix.

**Comment by uuphoria2** [comment]
As I am using the sm64js-mmo-server repo and basically want to serve it from my files to deploy it officially to https://mmo.sm64jsarchive.com for production via Actix. (Also sm64js-mmo-server was tested on my local device via git clone and I added everything needed like the client submodule as I used git clone recurse submodules which basically when its git cloned it includes also gitclones all submodules into their directory in this case its `/client/`)

**Comment by uuphoria2** [comment]
As I am using the sm64js-mmo-server repo I basically want to serve it from my files to deploy it officially to https://mmo.sm64jsarchive.com for production via Actix. (Also sm64js-mmo-server was tested on my local device via git clone and I added everything needed like the client submodule as I used git clone recurse submodules which basically when its git cloned it includes also gitclones all submodules into their directory in this case its `/client/` which it works perfectly fine and is stable.)

**Comment by uuphoria2** [comment]
As I am using the sm64js-mmo-server repo I basically want to serve it from my files to deploy it officially to https://mmo.sm64jsarchive.com for production via Actix on the sm64js-mmo-server repo on my device which is perfectly setup already.(Also sm64js-mmo-server was tested on my local device via git clone and localhost aka http://localhost:3060 here for sm64js-mmo-server and I added everything needed like the client submodule as I used git clone recurse submodules which basically when its git cloned it includes also gitclones all submodules into their directory in this case its `/client/` which sm64js-mmo-server works perfectly fine and is stable on my own device So this could actually work perfectly fine and in a stable way which it could actually succesfully serve to https://mmo.sm64jsarchive.com with functioning MMO servers as I set up postgres already to work too using Amazon AWS.)

**Comment by uuphoria2** [comment]
I found out how to use nginx
